INSERT INTO language_values
	(language_code, language_key, language_value)
VALUES
	('en', 'START_MESSAGE', 'Congratulations! We are very glad that you have joined our service.This'
	||' bot will help you track current exchange rates from different banks. The bot can provide '
	||'information both on request and automatically according to the specified schedule. To configure'
	||' the bots convenient operating mode, use the "Settings" menu section.'),
	('en', 'HEADSIGN_MAINMENU', 'How can I help you? ⤵'),
	('en', 'HEADSIGN_OPTIONS', 'Settings'),
	('en', 'HEADSIGN_INFO', 'Your settings:'),
	('en', 'HEADSIGN_COMMASYMBOLS', 'Symbols after comma'),
	('en', 'HEADSIGN_BANKSMENU', 'Choose your bank'),
	('en', 'HEADSIGN_CURRENCYMENU', 'Choose your currency'),
	('en', 'HEADSIGN_NOTIFICATIONTIME', 'Select notification time'),
	('en', 'HEADSIGN_USERTIME', 'Enter the number of hours now ⤵'),
	('en', 'BACK', '⬅ Back'),
	('en', 'MAIN_MENU', 'Main menu'),
	('en', 'MAIN_GET_INFO', 'Currency rates'),
	('en', 'MAIN_OPTIONS', 'Options'),
	('en', 'OPTIONS_NUMBER_SYMBOL_AFTER_COMMA', 'Symbols after comma'),
	('en', 'OPTIONS_BANK', 'Bank'),
	('en', 'OPTIONS_CURRENCY', 'Currency'),
	('en', 'OPTIONS_NOTIFICATIONS', 'Notification time'),
	('en', 'OPTIONS_USERTIME', 'Set your time'),
	('en', 'NUMBERS_2', '2'),
	('en', 'NUMBERS_3', '3'),
	('en', 'NUMBERS_4', '4'),
	('en', 'CURRENCY_USD', 'USD'),
	('en', 'CURRENCY_EUR', 'EUR'),
	('en', 'MESSAGE_SERVICE_HEADER', 'Currency from %s:'),
	('en', 'MESSAGE_SERVICE_BODY_ROW', '\n%s/UAH:\nBuy\t%s\nSell\t%s'),
	('en', 'MESSAGE_SERVICE_BANK_RATES_NOT_FOUND', 'At the moment, there is no information about the exchange rates of "%s". Please select another bank in the settings.'),
	('en', 'MESSAGE_CURRENCY_NOT_SELECTED', 'To get information about the exchange rate, please select the currency you are interested in in the settings.'),
	('en', 'CRYPTOCURRENCY', 'Cryptocurrency'),
	('en', 'NBU', 'NBU'),
	('en', 'PRIVATBANK', 'Privatbank'),
	('en', 'MONOBANK', 'Monobank'),
	('en', 'OSCHADBANK', 'Oschadbank'),
	('en', 'ALERT_9', '9:00'),
	('en', 'ALERT_10', '10:00'),
	('en', 'ALERT_11', '11:00'),
	('en', 'ALERT_12', '12:00'),
	('en', 'ALERT_13', '13:00'),
	('en', 'ALERT_13', '13:00'),
	('en', 'ALERT_14', '14:00'),
	('en', 'ALERT_15', '15:00'),
	('en', 'ALERT_16', '16:00'),
	('en', 'ALERT_17', '17:00'),
	('en', 'ALERT_18', '18:00'),
	('en', 'ALERT_AFTER_CHANGE', 'After change'),
	('en', 'ALERT_OFF', 'Switch Off'),
	('en', 'OPTIONS_LANGUAGE', 'Language'),
	('en', 'UA_BUTTON', 'Українська'),
	('en', 'EN_BUTTON', 'English'),
	('en', 'PL_BUTTON', 'Polski'),
	('en', 'TIME_0', '00'),
	('en', 'TIME_1', '01'),
	('en', 'TIME_2', '02'),
	('en', 'TIME_3', '03'),
	('en', 'TIME_4', '04'),
	('en', 'TIME_5', '05'),
	('en', 'TIME_6', '06'),
	('en', 'TIME_7', '07'),
	('en', 'TIME_8', '08'),
	('en', 'TIME_9', '09'),
	('en', 'TIME_10', '10'),
	('en', 'TIME_11', '11'),
	('en', 'TIME_12', '12'),
	('en', 'TIME_13', '13'),
	('en', 'TIME_14', '14'),
	('en', 'TIME_15', '15'),
	('en', 'TIME_16', '16'),
	('en', 'TIME_17', '17'),
	('en', 'TIME_18', '18'),
	('en', 'TIME_19', '19'),
	('en', 'TIME_20', '20'),
	('en', 'TIME_21', '21'),
	('en', 'TIME_22', '22'),
	('en', 'TIME_23', '23'),
	('en', 'BITCOIN', 'Bitcoin'),
	('en', 'ETHEREUM', 'Ethereum'),
	('en', 'HOME', 'Home'),
	('en', 'HELP', 'Help'),
	('en', 'HELP_MESSAGE', 'This bot will help you track current exchange rates from different banks. The bot can provide information both on request and automatically according to the specified schedule.\n\n To get the exchange rate of the selected bank, click the "Currency rates" button in the main menu\n\n To configure the bots convenient operating mode, use the "Settings" menu section.')
;

