INSERT INTO language_values
	(language_code, language_key, language_value)
VALUES
	('uk', 'START_MESSAGE', 'Щиро вітаю! Ми дуже раді, що ви приєдналися до нашого сервісу.\nЦей бот допоможе вам відстежувати поточні курси валют різних банків. Бот може надавати інформацію як за запитом, так і автоматично за заданим графіком.\nЩоб налаштувати зручний режим роботи ботів, скористайтеся розділом меню «Налаштування».'),
	('uk', 'HEADSIGN_MAINMENU', 'Чим Вам допомогти? ⤵'),
	('uk', 'HEADSIGN_OPTIONS', 'Налаштування'),
	('uk', 'HEADSIGN_INFO', 'Ваші налаштування:'),
	('uk', 'HEADSIGN_COMMASYMBOLS', 'Знаків після коми'),
	('uk', 'HEADSIGN_BANKSMENU', 'Який банк Вас цікавить?'),
	('uk', 'HEADSIGN_CURRENCYMENU', 'Яка валюта Вас цікавить?'),
	('uk', 'HEADSIGN_NOTIFICATIONTIME', 'Коли сповістити?'),
	('uk', 'HEADSIGN_USERTIME', 'Ваш час зараз ⤵'),
	('uk', 'BACK', '⬅ Назад'),
	('uk', 'MAIN_MENU', 'Головне меню'),
	('uk', 'MAIN_GET_INFO', 'Курс валют'),
	('uk', 'MAIN_OPTIONS', 'Налаштування'),
	('uk', 'OPTIONS_NUMBER_SYMBOL_AFTER_COMMA', 'Точність'),
	('uk', 'OPTIONS_BANK', 'Банк'),
	('uk', 'OPTIONS_CURRENCY', 'Валюта'),
	('uk', 'OPTIONS_NOTIFICATIONS', 'Час сповіщень'),
	('uk', 'OPTIONS_USERTIME', 'Часова зона'),
	('uk', 'NUMBERS_2', '2'),
	('uk', 'NUMBERS_3', '3'),
	('uk', 'NUMBERS_4', '4'),
	('uk', 'CURRENCY_USD', 'Долар США'),
	('uk', 'CURRENCY_EUR', 'Євро'),
	('uk', 'MESSAGE_SERVICE_HEADER', 'Курс в %s:'),
	('uk', 'MESSAGE_SERVICE_BODY_ROW', '\n%s/UAH:\nКупівля\t%s\nПродаж\t%s'),
	('uk', 'MESSAGE_SERVICE_BANK_RATES_NOT_FOUND', 'На даний момент інформація про курси валют %s відсутня. Будь ласка, оберіть  в налаштуваннях інший банк.'),
	('uk', 'MESSAGE_CURRENCY_NOT_SELECTED', 'Щоб отримати інформацію про курс валют, будь ласка, оберіть в налаштуваннях валюту, що вас цікавить.'),
	('uk', 'CRYPTOCURRENCY', 'Кріптовалюта'),
	('uk', 'NBU', 'НБУ'),
	('uk', 'PRIVATBANK', 'ПриватБанк'),
	('uk', 'MONOBANK', 'Монобанк'),
	('uk', 'OSCHADBANK', 'Oschadbank'),
	('uk', 'ALERT_9', '9:00'),
	('uk', 'ALERT_10', '10:00'),
	('uk', 'ALERT_11', '11:00'),
	('uk', 'ALERT_12', '12:00'),
	('uk', 'ALERT_13', '13:00'),
	('uk', 'ALERT_13', '13:00'),
	('uk', 'ALERT_14', '14:00'),
	('uk', 'ALERT_15', '15:00'),
	('uk', 'ALERT_16', '16:00'),
	('uk', 'ALERT_17', '17:00'),
	('uk', 'ALERT_18', '18:00'),
	('uk', 'ALERT_AFTER_CHANGE', 'Після зміни'),
	('uk', 'ALERT_OFF', 'Вимкнути'),
	('uk', 'OPTIONS_LANGUAGE', 'Мова'),
	('uk', 'UA_BUTTON', 'Українська'),
	('uk', 'EN_BUTTON', 'English'),
	('uk', 'PL_BUTTON', 'Polski'),
	('uk', 'TIME_0', '00'),
	('uk', 'TIME_1', '01'),
	('uk', 'TIME_2', '02'),
	('uk', 'TIME_3', '03'),
	('uk', 'TIME_4', '04'),
	('uk', 'TIME_5', '05'),
	('uk', 'TIME_6', '06'),
	('uk', 'TIME_7', '07'),
	('uk', 'TIME_8', '08'),
	('uk', 'TIME_9', '09'),
	('uk', 'TIME_10', '10'),
	('uk', 'TIME_11', '11'),
	('uk', 'TIME_12', '12'),
	('uk', 'TIME_13', '13'),
	('uk', 'TIME_14', '14'),
	('uk', 'TIME_15', '15'),
	('uk', 'TIME_16', '16'),
	('uk', 'TIME_17', '17'),
	('uk', 'TIME_18', '18'),
	('uk', 'TIME_19', '19'),
	('uk', 'TIME_20', '20'),
	('uk', 'TIME_21', '21'),
	('uk', 'TIME_22', '22'),
	('uk', 'TIME_23', '23'),
	('uk', 'BITCOIN', 'Bitcoin'),
	('uk', 'ETHEREUM', 'Ethereum'),
	('uk', 'HOME', 'Додому'),
	('uk', 'HELP', 'Довідка'),
	('uk', 'HELP_MESSAGE', 'Цей бот допоможе Вам відслідковувати актульні курси валют з різних банків. Бот може надавати інформацію, як по запиту, так і автоматично за вказаним розкладом. \n\nДля отримання курсу обраного банку натисність в головному меню кнопку "Курс валют"\n\nЩоб налаштувати зручний режим роботи бота, скористайтеся розділом меню "Налаштування".')
;

