INSERT INTO language_values
	(language_code, language_key, language_value)
VALUES
	('pl', 'START_MESSAGE', 'Gratulacje! Bardzo się cieszymy, że dołączyłeś do naszego serwisu. Ten bot pomoże Ci śledzić aktualne kursy walut z różnych banków. Bot może przekazywać informacje zarówno na żądanie, jak i automatycznie według określonego harmonogramu. Aby skonfigurować wygodny tryb pracy bota, skorzystaj z sekcji menu "„"Ustawienia".'),
	('pl', 'HEADSIGN_MAINMENU', 'Jak mogę ci pomóc? ⤵'),
	('pl', 'HEADSIGN_OPTIONS', 'Ustawienia'),
	('pl', 'HEADSIGN_INFO', 'Wasze ustawienia'),
	('pl', 'HEADSIGN_COMMASYMBOLS', 'Symbole po przecinku'),
	('pl', 'HEADSIGN_BANKSMENU', 'Wybierz swój bank'),
	('pl', 'HEADSIGN_CURRENCYMENU', 'Wybierz swoją walutę'),
	('pl', 'HEADSIGN_NOTIFICATIONTIME', 'Wybierz godzinę powiadomienia'),
	('pl', 'HEADSIGN_USERTIME', 'Wprowadź teraz swoje godziny ⤵'),
	('pl', 'BACK', '⬅ Wróć'),
	('pl', 'MAIN_MENU', 'Menu główne'),
	('pl', 'MAIN_GET_INFO', 'Kurs wymiany'),
	('pl', 'MAIN_OPTIONS', 'Opcje'),
	('pl', 'OPTIONS_NUMBER_SYMBOL_AFTER_COMMA', 'Symbole po przecinku'),
	('pl', 'OPTIONS_BANK', 'Bank'),
	('pl', 'OPTIONS_CURRENCY', 'Waluta'),
	('pl', 'OPTIONS_NOTIFICATIONS', 'Czas powiadomienia'),
	('pl', 'OPTIONS_USERTIME', 'Swój czas'),
	('pl', 'NUMBERS_2', '2'),
	('pl', 'NUMBERS_3', '3'),
	('pl', 'NUMBERS_4', '4'),
	('pl', 'CURRENCY_USD', 'USD'),
	('pl', 'CURRENCY_EUR', 'EUR'),
	('pl', 'MESSAGE_SERVICE_HEADER', 'Waluta od %s:'),
	('pl', 'MESSAGE_SERVICE_BODY_ROW', '\n%s/UAH:\nKupić\t%s\nSprzedać\t%s'),
	('pl', 'MESSAGE_SERVICE_BANK_RATES_NOT_FOUND', 'Informacje o kursach walut dla banku "%s" nieobecny! Proszę wybrać inny bank w ustawieniach.'),
	('pl', 'MESSAGE_CURRENCY_NOT_SELECTED', 'Aby uzyskać informacje o kursie walut, wybierz w ustawieniach interesującą Cię walutę.'),
	('pl', 'CRYPTOCURRENCY', 'Kryptowaluty'),
	('pl', 'NBU', 'NBU'),
	('pl', 'PRIVATBANK', 'Privatbank'),
	('pl', 'MONOBANK', 'Monobank'),
	('pl', 'OSCHADBANK', 'Oschadbank'),
	('pl', 'ALERT_9', '9:00'),
	('pl', 'ALERT_10', '10:00'),
	('pl', 'ALERT_11', '11:00'),
	('pl', 'ALERT_12', '12:00'),
	('pl', 'ALERT_13', '13:00'),
	('pl', 'ALERT_13', '13:00'),
	('pl', 'ALERT_14', '14:00'),
	('pl', 'ALERT_15', '15:00'),
	('pl', 'ALERT_16', '16:00'),
	('pl', 'ALERT_17', '17:00'),
	('pl', 'ALERT_18', '18:00'),
	('pl', 'ALERT_AFTER_CHANGE', 'Po zmianie'),
	('pl', 'ALERT_OFF', 'Wyłączyć'),
	('pl', 'OPTIONS_LANGUAGE', 'Język'),
	('pl', 'UA_BUTTON', 'Українська'),
	('pl', 'EN_BUTTON', 'English'),
	('pl', 'PL_BUTTON', 'Polski'),
	('pl', 'TIME_0', '00'),
	('pl', 'TIME_1', '01'),
	('pl', 'TIME_2', '02'),
	('pl', 'TIME_3', '03'),
	('pl', 'TIME_4', '04'),
	('pl', 'TIME_5', '05'),
	('pl', 'TIME_6', '06'),
	('pl', 'TIME_7', '07'),
	('pl', 'TIME_8', '08'),
	('pl', 'TIME_9', '09'),
	('pl', 'TIME_10', '10'),
	('pl', 'TIME_11', '11'),
	('pl', 'TIME_12', '12'),
	('pl', 'TIME_13', '13'),
	('pl', 'TIME_14', '14'),
	('pl', 'TIME_15', '15'),
	('pl', 'TIME_16', '16'),
	('pl', 'TIME_17', '17'),
	('pl', 'TIME_18', '18'),
	('pl', 'TIME_19', '19'),
	('pl', 'TIME_20', '20'),
	('pl', 'TIME_21', '21'),
	('pl', 'TIME_22', '22'),
	('pl', 'TIME_23', '23'),
	('pl', 'BITCOIN', 'Bitcoin'),
	('pl', 'ETHEREUM', 'Ethereum'),
	('pl', 'HOME', 'Dom'),
	('pl', 'HELP', 'Pomoc'),
	('pl', 'HELP_MESSAGE', 'Ten bot pomoże Ci śledzić aktualne kursy walut z różnych banków. Bot może przekazywać informacje zarówno na żądanie, jak i automatycznie według określonego harmonogramu.\n\nAby uzyskać kurs wybranego banku, kliknij przycisk "Kurs wymiany" w menu głównym\n\nAby skonfigurować wygodny tryb pracy bota, skorzystaj z sekcji menu "Ustawienia".')
;

